apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-srtknk
  labels:
    name: server
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: server-srtknk.cxnam.ews.en.internal
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: server-srtknk
              servicePort: 8000
